# Defines a default set of lint rules for Flutter projects.
# For details, see https://pub.dev/packages/flutter_lints.
include: package:flutter_lints/flutter.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
linter:
  rules:
    # Добавьте пользовательские правила здесь, если нужно
    - camel_case_types
    - prefer_const_constructors
    - avoid_print

analyzer:
  exclude:
    - build/**
    - .dart_tool/**