name: xmpp_client_web

description: "Xmpp Stone is lightweight XMPP client web library written completely in Dart."

version: 0.5.3-dev.1

homepage: https://github.com/Xatiko540/xmpp_dart

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=1.10.0'

#dependencies:
#  path: ^1.4.1
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
      sdk: flutter
  xml: ^6.5.0
  cryptoutils: ^0.5.0
  crypto: ^3.0.5
  synchronized: ^3.2.0
  tuple: ^2.0.2
  unorm_dart: ^0.3.0
  image: ^4.2.0
  quiver: ^3.2.2 #hash code generator
  console: ^4.1.0 #for example
  intl: ^0.20.1
  collection: ^1.18.0
  universal_io: ^2.2.2
  web_socket_channel: ^3.0.1
  flutter_lints: ^5.0.0

dev_dependencies:
  test: ^1.25.2
  mockito: ^5.4.4



include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - avoid_print



flutter:
  plugin:
    platforms:
      web:
        pluginClass: XmppClientWebPlugin
        fileName: src/web/xmpp_client_web.dart